### ISSUE TITLE
List of Articles - script?

### ISSUE THREAD

**Issue by socialresearchist** [FBartos/zcurve#15]
Thank you for your work in making Psychology research more accountable and valid.

It is hinted in replicationindex.com that there is a script to take into from a pdf>doc>list all the data from a list of author articles without doing it manually.

Is this available?

**Comment by FBartos** [comment]
Hi, I'm not completely sure which script you have in mind (and it's not a part of the package). I would try asking Uli directly (ulrich.schimmack@utoronto.ca)

Cheers,
Frantisek
