### ISSUE TITLE
plot zcurve object using ggplot(2)

### ISSUE THREAD

**Issue by Yefeng0920** [FBartos/zcurve#17]
Hey, two great researchers @DominikVogel @FBartos, just want to know if the ggplot version of plotting zcurve object is available? If not, can you instruct me how to do it?

Best,
Yefeng

**Comment by FBartos** [comment]
Hi @Yefeng0920 ,

It's not in the CRAN version yet -- I will check whether there are further changes needed and aim to getting it to CRAN sometime next week.

Cheers,
Frantisek

**Comment by FBartos** [comment]
So, the ggplot figure option was now added to the new CRAN version (2.4.0)

```
library(zcurve)
fit.EM  <- zcurve(OSC.z)
plot(fit.EM, plot_type = "ggplot")
```
