### ISSUE TITLE
Misleading error message when empty vector is passed

### ISSUE THREAD

**Issue by LukasWallrich** [FBartos/zcurve#22]
I use `zcurve` in an app, and took quite a long time to figure out what was going on in a case like the below - maybe there could be a less misleading/more explicit error message?

``` r
zcurve::zcurve(z = numeric(0))
#> Error in zcurve::zcurve(z = numeric(0)): It looks like you are entering p-values rather than z-scores. To use p-values, explicitly name your argument 'zcurve(p = [vector of p-values])'
```

<sup>Created on 2024-05-23 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by FBartos** [comment]
Hi Lukas,

Thanks for reporting, I see the issue and I will fix the input check to also deal with zero length inputs.

Frantisek

**Comment by FBartos** [comment]
Does this error helps with debuging? 
```
> zcurve::zcurve(z = numeric(0))
Error in zcurve::zcurve(z = numeric(0)) : 
  An empty input was passed as z-scores.
```

**Comment by LukasWallrich** [comment]
Perfect, thanks!

**Comment by FBartos** [comment]
It's on the way to CRAN.
