### ISSUE TITLE
Prepping Data for Z Curve (Best Approach?)

### ISSUE THREAD

**Issue by peclayson** [FBartos/zcurve#25]
Hi @FBartos,

I have extracted test test statistics, degrees of freedom, and test values in preparation for a zcurve analysis. I'm trying to understand what the "best" approach is to prepare the statistics for the z curve. The data have been formatted to be put into `zcurve_data`. 

The function provides the precise _p_ values. Then I can use `zcurve(p = df_zcurve_data$precise$p)` to run a z-curve analysis. Does this make sense? 

I couldn't find an example of using `zcurve_data` and then the approach for passing this to `zcurve`, so I wanted to double check.

Thanks for your help!
Peter

**Comment by FBartos** [comment]
Hi Peter,

it really depends on exactly what information you have at hand. If you can compute p-values for each data point directly, then there is nothing stopping you from using `zcurve(p = p)`. If you have some censored p-values, then using `zcurve(data = df_zcurve_data)` might be advantageous (extracting the precise p-values from the `zcurve_data` object directly does not make that much sense to me though---maybe there is something that I'm missing?) .

Cheers,
Frantisek

**Comment by peclayson** [comment]
I'm sure you're not missing anything. I likely just confused both of us.

I have 100+ observations of test statistics and test values (no _p_ values though), formatted as follows: 
`c("F(2,38)=0.789", "F(2,46)=7.55", "F(1,61)=8.33", "F(1.83,49.4)=3.32", "F(1,52)=4.83", "chi(1)=28.72")` etc.

Since I do not have _z_ scores or _p_ values, I am using the `zcurve_data` function to calculate the _p_ values and then plug those into `zcurve` for analysis. 

```

zcurve_prepped <- zcurve_data(zcrv_stats, stat_precise = 1)

fit <- zcurve(data = zcurve_prepped)

```

That is the intended application `data = zcurve_prepped`, correct? Not `zcurve(p = zcurve_prepped$precise$p)`?

I apologize. I think I confused myself thinking I need to operate directly on the p values, rather than using `data = zcurve_prepped`.  



Peter

**Comment by FBartos** [comment]
Hi Peter,

No worries; this is indeed the function's intended use!

I will close it as solved. Please, reopen it if you have any further questions.
Cheers,
Frantisek
